/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WavPlayerPositionPanel.java
 *
 * Created on Dec 13, 2011, 12:16:52 AM
 */
package org.rwshop.swing.audio.wav;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.robokind.api.audio.AudioProgressListener;
import org.robokind.api.audio.WavPlayer;

/**
 *
 * @author matt
 */
public class WavPlayerPositionPanel extends javax.swing.JPanel {
    private WavListener myListener;
    private long myTotalFrameCount;
    /** Creates new form WavPlayerPositionPanel */
    public WavPlayerPositionPanel() {
        initComponents();
//        myPositionSlider.setPaintLabels(false);
    }
    
    public void init(WavPlayer player){                               
        try{
            myTotalFrameCount = player.getLengthFrames();
            myListener = new WavListener();
            player.addAudioProgressListener(myListener);
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPositionSlider = new javax.swing.JSlider();

        myPositionSlider.setMaximum(10000);
        myPositionSlider.setValue(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPositionSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPositionSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider myPositionSlider;
    // End of variables declaration//GEN-END:variables

    private class WavListener implements AudioProgressListener{

        @Override
        public void update(long frame, double usec) {
            double val = (double)frame/(double)myTotalFrameCount;
            val = val*myPositionSlider.getMaximum();
            myPositionSlider.setValue((int)val);
        }
        
    }
    
    private class SliderListener implements ChangeListener{
        private WavPlayer myPlayer;
        
        @Override
        public void stateChanged(ChangeEvent e) {
        }
        
    }
}
