/*
 * Copyright 2014 the RoboWorkshop Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * AQTTSFrame.java
 *
 * Created on Jul 28, 2011, 1:37:26 AM
 */
package org.rwshop.swing.speech;

import org.mechio.api.speech.messaging.RemoteSpeechServiceClient;


/**
 *
 * @author Matthew Stevenson <www.roboworkshop.org>
 */
public class AQTTSFrame extends javax.swing.JFrame {

    /** Creates new form AQTTSFrame */
    public AQTTSFrame() {
        initComponents();
    }
    
    public void setTTSFacade(RemoteSpeechServiceClient speechclient){
        myAQTTSPanel.setAQTTSFacade(speechclient);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myAQTTSPanel = new org.rwshop.swing.speech.AQTTSPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myAQTTSPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myAQTTSPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AQTTSFrame().setVisible(true);
            }
        });
    }
    
    public static void show(final RemoteSpeechServiceClient speechService, final String path) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AQTTSFrame frame = new AQTTSFrame();
                frame.setTTSFacade(speechService);
                frame.setTitle("TTS Window");
                frame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.rwshop.swing.speech.AQTTSPanel myAQTTSPanel;
    // End of variables declaration//GEN-END:variables
}
